import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { Card } from '../components/Card'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [dragonShips, setDragonShips] = useState<{}[]>([])
  const [rockets, setRockets] = useState<{}[]>([])
  const fetchShips = async () => {
    const fetchData = await fetch(
      'https://api.spacexdata.com/v4/dragons?limit=5'
    )
    const fetchJson = await fetchData.json()
    setDragonShips(fetchJson)
  }
  const fetchRockets = async () => {
    const fetchData = await fetch('https://api.spacexdata.com/v4/rockets')
    const fetchJson = await fetchData.json()
    setRockets(fetchJson)
  }
  useEffect(() => {
    fetchShips()
    fetchRockets()
  }, [])
  console.log(rockets)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>SpaceX API Practice</a>
        </h1>

        <p className={styles.description}>
          You can see different ships retrieved from the SpaceX Open Source API{' '}
        </p>

        <section>
          <h2 className={styles.description}>Dragon Capsules</h2>
          <div className={styles.grid}>
            {dragonShips.map(element => (
              <Card element={element} key={element.name} />
            ))}
          </div>
        </section>

        <section>
          <h2 className={styles.description}>Rockets Capsules</h2>
          <div className={styles.grid}>
            {rockets.map(element => (
              <Card element={element} key={element.name} />
            ))}
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
