import { NextPage } from 'next'
import Head from 'next/head'
import axios from 'axios'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { Card } from '../components/Card'
import styles from '../styles/Home.module.css'

interface iElement {
  id: string
  name: string
  flickr_images?: string[]
  image?: string
  type: string
  diameter: {
    feet: number
    meters: number
  }
  heat_shield?: {
    material: string
  }
}

const Home: NextPage<{
  dragonShips: iElement[]
  rockets: iElement[]
  ships: iElement[]
}> = ({ dragonShips, rockets, ships }) => {
  console.log(dragonShips)
  return (
    <div className={styles.container}>
      <Head>
        <title>Spacex API practice by Yosef Blandin</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{' '}
          <a href='https://nextjs.org'>Yosef Blandin SpaceX API Practice</a>
        </h1>

        <p className={styles.description}>
          You can see different ships retrieved from the SpaceX Open Source API{' '}
        </p>

        <h2 className={styles.description}>Dragon Capsules</h2>
        <section className={styles.grid}>
          {dragonShips?.map(element => (
            <Card element={element} key={element.name} />
          ))}
        </section>

        <h2 className={styles.description}>Rockets</h2>
        <section className={styles.grid}>
          {rockets?.map(element => (
            <Card element={element} key={element.name} />
          ))}
        </section>

        <h2 className={styles.description}>Ships</h2>
        <section className={styles.grid}>
          {ships?.map(element => (
            <Card element={element} key={element.name} />
          ))}
        </section>
      </main>
    </div>
  )
}

export async function getServerSideProps () {
  let data = await fetch('https://api.spacexdata.com/v4/dragons?limit=5')
  let data1 = await fetch('https://api.spacexdata.com/v4/rockets')
  let data2 = await fetch('https://api.spacexdata.com/v4/ships')
  let dragonShips = await data.json()
  let rockets = await data1.json()
  let ships = await data2.json()

  return {
    props: {
      dragonShips,
      rockets,
      ships
    }
  }
}

export default Home
